
  CREATE TABLE "ARCHIVE"."DOCARCH" 
   (	"ARCH_KEY" CHAR(16) NOT NULL ENABLE, 
	"DOC_ID" CHAR(36) NOT NULL ENABLE, 
	"VERSION_NO" NUMBER(5,0) NOT NULL ENABLE, 
	"RETENTION_CLASS" CHAR(4) NOT NULL ENABLE, 
	"LAST_ACCESS_TS" TIMESTAMP (9) NOT NULL ENABLE, 
	"STORAGE_CHARGE" NUMBER(31,8) NOT NULL ENABLE, 
	"UNIT_RATE" NUMBER(31,8) NOT NULL ENABLE, 
	"OWNER_NAME" RAW(40) NOT NULL ENABLE, 
	"DISPOSITION_DT" RAW(8) NOT NULL ENABLE, 
	"LEGAL_HOLD_FLAG" CHAR(1) NOT NULL ENABLE, 
	"CHECKSUM_ALG" CHAR(8) NOT NULL ENABLE, 
	"CONTENT_SHA256" CHAR(64) NOT NULL ENABLE, 
	"BYTE_SIZE" NUMBER(19,0) NOT NULL ENABLE, 
	"SOURCE_SYS" CHAR(3) NOT NULL ENABLE, 
	 CONSTRAINT "CK_DOCARCH_HOLD" CHECK (LEGAL_HOLD_FLAG IN ('Y', 'N')) ENABLE, 
	 CONSTRAINT "PK_DOCARCH" PRIMARY KEY ("ARCH_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_DOCARCH_RETNPLCY" FOREIGN KEY ("RETENTION_CLASS")
	  REFERENCES "ARCHIVE"."RETNPLCY" ("POLICY_CODE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 