
  CREATE TABLE "ARCHIVE"."CLASS_TOTAL_SNAP" 
   (	"SNAP_TS" TIMESTAMP (9) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"AS_OF_DT" DATE NOT NULL ENABLE, 
	"RETENTION_CLASS" CHAR(4) NOT NULL ENABLE, 
	"DOC_COUNT" NUMBER(12,0) NOT NULL ENABLE, 
	"CHARGE_TOTAL" NUMBER(31,8) NOT NULL ENABLE, 
	 CONSTRAINT "PK_CLASS_TOTAL_SNAP" PRIMARY KEY ("SNAP_TS", "RETENTION_CLASS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 