
  CREATE OR REPLACE EDITIONABLE TRIGGER "ARCHIVE"."TRG_DOCARCH_HOLD_AUDIT" 
AFTER UPDATE OF LEGAL_HOLD_FLAG ON ARCHIVE.DOCARCH
FOR EACH ROW
 WHEN (NEW.LEGAL_HOLD_FLAG <> OLD.LEGAL_HOLD_FLAG) DECLARE
    v_actor  VARCHAR2(12) := SUBSTR(SYS_CONTEXT('USERENV', 'SESSION_USER'), 1, 12);
    v_ip     VARCHAR2(15) := SUBSTR(NVL(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), '0.0.0.0'), 1, 15);
BEGIN
    INSERT INTO ARCHIVE.FILEAUD (
        AUDIT_KEY, ARCH_KEY, EVENT_TYPE, EVENT_TS, ACTOR_ID, RETENTION_CLASS,
        DISPOSITION_CODE, CLIENT_IP, DETAIL_TEXT)
    VALUES (
        'TRG' || LPAD(TO_CHAR(ARCHIVE.SEQ_FILEAUD_TRG.NEXTVAL), 17, '0'),
        :NEW.ARCH_KEY,
        DECODE(:NEW.LEGAL_HOLD_FLAG, 'Y', 'HOLD', 'RLSE'),
        SYSTIMESTAMP,
        v_actor,
        :NEW.RETENTION_CLASS,
        ARCHIVE.RETENTION_PKG.DISPOSITION_CODE(:NEW.RETENTION_CLASS, :NEW.LAST_ACCESS_TS, :NEW.LEGAL_HOLD_FLAG),
        v_ip,
        SUBSTR(DECODE(:NEW.LEGAL_HOLD_FLAG, 'Y', 'HOLD placed', 'HOLD released') || ' v' || :NEW.VERSION_NO, 1, 40));
END;
ALTER TRIGGER "ARCHIVE"."TRG_DOCARCH_HOLD_AUDIT" ENABLE