
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ARCHIVE"."V_ELIGIBLE_DOCS" ("ARCH_KEY", "DOC_ID", "VERSION_NO", "RETENTION_CLASS", "SOR_CLASS", "LAST_ACCESS_TS", "STORAGE_CHARGE", "BYTE_SIZE", "LEGAL_HOLD_FLAG", "DISPOSITION_DUE", "DISPOSITION_DT_STORED", "DISPOSITION_CODE") AS 
  SELECT d.ARCH_KEY,
       d.DOC_ID,
       d.VERSION_NO,
       d.RETENTION_CLASS,
       ARCHIVE.RETENTION_PKG.RESOLVE_CLASS(d.RETENTION_CLASS)                              AS SOR_CLASS,
       d.LAST_ACCESS_TS,
       d.STORAGE_CHARGE,
       d.BYTE_SIZE,
       d.LEGAL_HOLD_FLAG,
       ARCHIVE.RETENTION_PKG.DISPOSITION_DATE(d.LAST_ACCESS_TS, d.RETENTION_CLASS)         AS DISPOSITION_DUE,
       ARCHIVE.RETENTION_PKG.DISPOSITION_DT_TEXT(d.DISPOSITION_DT)                         AS DISPOSITION_DT_STORED,
       ARCHIVE.RETENTION_PKG.DISPOSITION_CODE(d.RETENTION_CLASS, d.LAST_ACCESS_TS, d.LEGAL_HOLD_FLAG)
                                                                                           AS DISPOSITION_CODE
  FROM ARCHIVE.DOCARCH d
 WHERE ARCHIVE.RETENTION_PKG.IS_ELIGIBLE(d.RETENTION_CLASS, d.LAST_ACCESS_TS, d.LEGAL_HOLD_FLAG) = 1