
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ARCHIVE"."V_LEGAL_HOLDS" ("ARCH_KEY", "DOC_ID", "RETENTION_CLASS", "LAST_ACCESS_TS", "OWNER_NAME", "LAST_HOLD_TS", "AUDIT_EVENTS") AS 
  SELECT d.ARCH_KEY,
       d.DOC_ID,
       d.RETENTION_CLASS,
       d.LAST_ACCESS_TS,
       NVL(UTL_RAW.CAST_TO_VARCHAR2(UTL_RAW.CONVERT(d.OWNER_NAME,
               'AMERICAN_AMERICA.WE8ISO8859P1', 'AMERICAN_AMERICA.WE8EBCDIC37')), '?')  AS OWNER_NAME,
       (SELECT MAX(f.EVENT_TS) FROM ARCHIVE.FILEAUD f
         WHERE f.ARCH_KEY = d.ARCH_KEY AND f.EVENT_TYPE = 'HOLD')                        AS LAST_HOLD_TS,
       (SELECT COUNT(*) FROM ARCHIVE.FILEAUD f WHERE f.ARCH_KEY = d.ARCH_KEY)            AS AUDIT_EVENTS
  FROM ARCHIVE.DOCARCH d
 WHERE d.LEGAL_HOLD_FLAG = 'Y'