
  CREATE TABLE "ARCHIVE"."FILEAUD" 
   (	"AUDIT_KEY" CHAR(20) NOT NULL ENABLE, 
	"ARCH_KEY" CHAR(16) NOT NULL ENABLE, 
	"EVENT_TYPE" CHAR(4) NOT NULL ENABLE, 
	"EVENT_TS" TIMESTAMP (9) NOT NULL ENABLE, 
	"ACTOR_ID" CHAR(12) NOT NULL ENABLE, 
	"RETENTION_CLASS" CHAR(4) NOT NULL ENABLE, 
	"DISPOSITION_CODE" CHAR(2) NOT NULL ENABLE, 
	"CLIENT_IP" CHAR(15) NOT NULL ENABLE, 
	"DETAIL_TEXT" VARCHAR2(40) NOT NULL ENABLE, 
	 CONSTRAINT "PK_FILEAUD" PRIMARY KEY ("AUDIT_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_FILEAUD_DOCARCH" FOREIGN KEY ("ARCH_KEY")
	  REFERENCES "ARCHIVE"."DOCARCH" ("ARCH_KEY") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  PARTITION BY RANGE ("EVENT_TS") INTERVAL (NUMTOYMINTERVAL(1, 'YEAR')) 
 (PARTITION "P_PRE2010"  VALUES LESS THAN (TIMESTAMP' 2010-01-01 00:00:00') SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ) 