
  CREATE TABLE "ARCHIVE"."RETNPLCY" 
   (	"POLICY_CODE" CHAR(4) NOT NULL ENABLE, 
	"POLICY_DESC" VARCHAR2(60) NOT NULL ENABLE, 
	"RETENTION_YEARS" NUMBER(5,0) NOT NULL ENABLE, 
	"SUCCESSOR_CODE" CHAR(4) NOT NULL ENABLE, 
	"ACTIVE_FLAG" CHAR(1) NOT NULL ENABLE, 
	"DISPOSITION_ACTION" CHAR(4) NOT NULL ENABLE, 
	"EFFECTIVE_TS" TIMESTAMP (9) NOT NULL ENABLE, 
	 CONSTRAINT "CK_RETNPLCY_ACTIVE" CHECK (ACTIVE_FLAG IN ('Y', 'N')) ENABLE, 
	 CONSTRAINT "CK_RETNPLCY_ACTION" CHECK (DISPOSITION_ACTION IN ('DEST', 'REVW', 'PERM')) ENABLE, 
	 CONSTRAINT "PK_RETNPLCY" PRIMARY KEY ("POLICY_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 