
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ARCHIVE"."V_CLASS_TOTALS" ("RETENTION_CLASS", "DOC_COUNT", "CHARGE_TOTAL", "OLDEST_ACCESS_TS", "NEWEST_ACCESS_TS") AS 
  SELECT l.SOR_CODE                          AS RETENTION_CLASS,
       COUNT(*)                            AS DOC_COUNT,
       ROUND(SUM(d.STORAGE_CHARGE), 8)     AS CHARGE_TOTAL,
       MIN(d.LAST_ACCESS_TS)               AS OLDEST_ACCESS_TS,
       MAX(d.LAST_ACCESS_TS)               AS NEWEST_ACCESS_TS
  FROM ARCHIVE.DOCARCH d
  JOIN ARCHIVE.V_POLICY_LINEAGE l ON l.POLICY_CODE = d.RETENTION_CLASS
 WHERE l.IN_CLOSED_SCHEDULE = 1
   AND d.LEGAL_HOLD_FLAG = 'N'
   AND d.LAST_ACCESS_TS < ARCHIVE.RETENTION_PKG.CUTOFF_TS()
 GROUP BY l.SOR_CODE