
  CREATE TABLE "MIGAUDIT"."PURGE_AUDIT" 
   (	"RUN_ID" VARCHAR2(64) NOT NULL ENABLE, 
	"TABLE_NAME" VARCHAR2(128) NOT NULL ENABLE, 
	"SOURCE_KEY" VARCHAR2(64) NOT NULL ENABLE, 
	"PURGED_AT" TIMESTAMP (9) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 CONSTRAINT "PK_PURGE_AUDIT" PRIMARY KEY ("RUN_ID", "TABLE_NAME", "SOURCE_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 