
  CREATE TABLE "MIGAUDIT"."PURGE_LOG" 
   (	"LOG_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"RUN_ID" VARCHAR2(64) NOT NULL ENABLE, 
	"LOGGED_AT" TIMESTAMP (9) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"SEVERITY" VARCHAR2(5) NOT NULL ENABLE, 
	"MESSAGE" VARCHAR2(4000) NOT NULL ENABLE, 
	 CONSTRAINT "CK_PURGE_LOG_SEV" CHECK (SEVERITY IN ('INFO', 'WARN', 'ERROR')) ENABLE, 
	 CONSTRAINT "PK_PURGE_LOG" PRIMARY KEY ("LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 