"""Emit .migration/census/coverage.md: every source object in exactly one bucket.

Buckets: `unit` (a migration unit owns it), `shared` (wave-0 reference), `rewrite`
(stored logic that becomes application/pipeline code), `proposed-unused` (present but
carrying no data, with the count as evidence), `excluded` (out of scope, with a reason).
The script asserts the object arithmetic instead of asserting it in prose.
"""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
CENSUS = ROOT / "census"
OUT = CENSUS / "coverage.md"


def load(n):
    return json.loads((CENSUS / f"{n}.json").read_text())


EXCLUSIONS = {
    "FIXTURE_META": ("excluded", ("estate bookkeeping (one row, an initialization "
                                 "timestamp); carries no business data")),
}

# Stored logic: destination decided per object, sized around the proc clusters.
STORED_LOGIC = {
    "PKG_OW_UTIL": ("rewrite", ("shared helpers: f_md5_uuid -> driver-side UUIDv5, "
                               "f_code_desc -> the denormalized code label, f_dt2str / "
                               "f_str2dt -> the load-time date parse, log_msg -> "
                               "application logging")),
    "PKG_PLANS": ("rewrite", ("fn_list_plans / fn_entitlement -> aggregation pipelines "
                             "(as-of filter on subscriptions); sp_change_plan -> a "
                             "transactional service method (multi-document txn)")),
    "PKG_RATING": ("rewrite", ("compute_rating / fn_usage_rating / fn_usage_summary -> one "
                              "$group aggregation over usage_events; sp_finalize_rating -> "
                              "a bulkWrite upsert into rating_periods.results[]")),
    "PKG_INVOICING": ("rewrite", ("compute_preview / fn_invoice_preview / fn_invoice_lines "
                                 "-> aggregation over rating_periods; sp_issue_invoice -> "
                                 "a single insert of the embedded invoice document")),
    "PKG_DUNNING": ("rewrite", ("fn_overdue_accounts -> aggregation; sp_schedule_dunning / "
                               "sp_suspend_overdue -> the scheduled job that replaces "
                               "JOB_NIGHTLY_DUNNING")),
}
TRIGGERS = {
    "TRG_CUSTOMER_MASTER_SEQ": ("retire", ("sequence-backed surrogate; cust_seq_no has no "
                                          "external consumer, `_id` is the natural key")),
    "TRG_ENTITY_ATTR_VALUE_SEQ": ("retire", ("EAV rows become array elements; the surrogate "
                                            "disappears with the table")),
    "TRG_BILLING_AUDIT_LOG_ID": ("retire", "replaced by ObjectId on the audit collection"),
    "TRG_CUSTOMER_MASTER_HIST": ("rewrite", ("full-row version history -> append to the "
                                            "embedded history[] array in the same update")),
    "TRG_SUBSCRIPTIONS_HIST": ("rewrite", "same pattern on subscriptions.history[]"),
    "TRG_SUB_NO_UNCANCEL": ("rewrite", ("genuine data-integrity invariant (a cancelled "
                                       "subscription cannot be reactivated): enforced by a "
                                       "JSON-schema validator plus a guarded update filter")),
    "TRG_USAGE_EVENTS_CHECK": ("rewrite", ("insert-time validation -> $jsonSchema validator "
                                          "on usage_events")),
}
JOBS = {
    "JOB_NIGHTLY_DUNNING": ("rewrite", ("scheduled application job calling the dunning "
                                       "service; not an Atlas trigger (it is batch work)")),
    "JOB_PURGE_AUDIT_LOG": ("rewrite", "replaced by a TTL index on billing_audit_log.logged_at"),
}
SEQUENCES = {
    "SEQ_CUSTOMER_MASTER": "retire — no external consumer of cust_seq_no",
    "SEQ_CUSTOMER_MASTER_HIST": "retire — history elements are keyed by position + hist_dt",
    "SEQ_SUBSCRIPTIONS_HIST": "retire — same",
    "SEQ_ENTITY_ATTR_VALUE": "retire — EAV rows become array elements",
    "SEQ_BILLING_AUDIT_LOG": "retire — ObjectId",
}


def main():
    spec = json.loads((ROOT / "03_mapping_spec.json").read_text())
    counts = load("exact_counts")
    objects = load("plsql_objects")
    idx = load("indexes")
    load("sequences")
    ap = json.loads((CENSUS / "access_patterns.json").read_text())

    table_owner = {}
    for c in spec["collections"]:
        sources = [c["root_table"]] + [e["child_table"] for e in c.get("embeds", [])]
        for t in sources:
            table_owner[t] = (c["unit"], c["collection"], c["wave"])

    lines = ["# Census coverage — every OW_BILLING object in exactly one bucket", "",
             "Generated by `.migration/tools/build_coverage.py` from the read-only census in",
             "`.migration/census/`. Buckets: **unit** (a migration unit owns it), **shared**",
             "(wave-0 reference data), **rewrite** (stored logic that becomes application or",
             "pipeline code), **retire** (has no target-side equivalent, by decision),",
             "**proposed-unused** (present but empty), **excluded** (out of scope).", "",
             "## Tables (20)", "",
             "| Table | Rows | Bucket | Owning unit | Target collection | Wave |",
             "|---|---:|---|---|---|---|"]
    for t, n in sorted(counts.items(), key=lambda x: -x[1]):
        if t in EXCLUSIONS:
            bucket, _reason = EXCLUSIONS[t]
            lines.append(f"| `{t}` | {n} | {bucket} | — | — | — |")
            continue
        unit, coll, wave = table_owner[t]
        bucket = "shared" if wave == 0 else "unit"
        lines.append(f"| `{t}` | {n:,} | {bucket} | `{unit}` | `{coll}` | {wave} |")
    lines += ["",
              (f"Arithmetic: {len(counts)} tables = "
              f"{len([t for t in counts if t not in EXCLUSIONS])} bucketed into units/shared "
              f"+ {len(EXCLUSIONS)} excluded. "
              f"Total source rows {sum(counts.values()):,}; total target documents "
              f"{sum(c['expected_documents'] for c in spec['collections']):,} "
              "(the difference is child rows that become embedded array elements)."), ""]

    lines += [f"## Columns ({len(load('columns'))})", "",
              "Every column lands in `fields` (mapped, including the repeating groups folded",
              "into subdocuments and the child tables folded into arrays) or `dropped` (with",
              "a reason) of exactly one collection — `build_mapping_spec.py` fails the build",
              "otherwise.", "",
              "| Collection | Mapped | Dropped |", "|---|---:|---:|"]
    mapped_total = dropped_total = 0
    for c in spec["collections"]:
        mapped = len(c.get("fields", [])) + sum(
            len(e.get("fields", [])) + len(e["key"]["source"]) for e in c.get("embeds", []))
        dropped = len(c.get("dropped", [])) + sum(
            len(e.get("dropped", [])) for e in c.get("embeds", []))
        mapped_total, dropped_total = mapped_total + mapped, dropped_total + dropped
        lines.append(f"| `{c['collection']}` | {mapped} | {dropped} |")
    excluded_tables = {t["table"] for t in spec["excluded_tables"]}
    excluded_cols = sum(1 for col in load("columns") if col["table_name"] in excluded_tables)
    lines.append(f"| _excluded tables_ | 0 | {excluded_cols} |")
    lines += ["", (f"Arithmetic: {mapped_total} mapped + {dropped_total} dropped + "
                   f"{excluded_cols} in excluded tables = "
                   f"{mapped_total + dropped_total + excluded_cols} of "
                   f"{len(load('columns'))} source columns.")]
    an = ap["customer_master_population"]["always_null_columns"]
    lines += ["",
              (f"**proposed-unused: {len(an)} of `CUSTOMER_MASTER`'s 155 columns are NULL in "
              f"all 25,000 rows** — the whole mailing-address block, `PHONE3`/`PHONE4`, "
              f"`EMAIL_2`/`EMAIL_3`, `FLAG_01..20`, `UDF_01..40`, `UDF_AMT_01..10`, "
              f"`UDF_DT_01..10` and 12 others. They are dropped with the population count as "
              f"evidence (`census/access_patterns.json#customer_master_population`), not "
              f"carried forward as empty fields. `CUSTOMER_MASTER_HIST` mirrors the same 155 "
              f"columns plus 3 history columns and holds 0 rows."), ""]

    lines += ["## Stored logic (5 packages / 19 routines, 7 triggers, 2 jobs, 5 sequences)",
              "",
              "All of it is owned by the `stored_logic` unit (wave 4). No PL/SQL is ported",
              "as-is; each object gets a destination.", "",
              "| Object | Type | Bucket | Destination |", "|---|---|---|---|"]
    for name, (bucket, dest) in STORED_LOGIC.items():
        lines.append(f"| `{name}` | package | {bucket} | {dest} |")
    for name, (bucket, dest) in TRIGGERS.items():
        lines.append(f"| `{name}` | trigger | {bucket} | {dest} |")
    for name, (bucket, dest) in JOBS.items():
        lines.append(f"| `{name}` | job | {bucket} | {dest} |")
    for name, dest in SEQUENCES.items():
        lines.append(f"| `{name}` | sequence | retire | {dest.split('— ')[1]} |")

    valid = [o for o in objects if o["status"] != "VALID"]
    lines += ["",
              (f"Compilation status: {len(objects)} PL/SQL objects, "
              f"{len(valid)} invalid. ROWID usage in stored code: "
              f"{len(load('rowid_usage'))} objects (the profile's ROWID trap does not apply "
              f"to this estate)."), ""]

    uniq = {i["index_name"] for i in idx}
    lines += [f"## Indexes ({len(uniq)})", "",
              "Source indexes are not migrated mechanically; the target index plan is per",
              "collection in `03_mapping_spec.json#collections.*.indexes` and is derived from",
              "the access-pattern evidence, not from the Oracle index list. Every unique",
              "constraint in the source does survive: as the collection key, a unique index,",
              "or a declared element invariant inside an embedded array, asserted by",
              "`build_mapping_spec.py`.", "",
              "## Behavioural baseline", "",
              "`procs/transcripts/` holds 24 recorded golden transcripts across the four",
              "business modules (rating 8, invoicing 6, plans 5, dunning 5) with a pinned",
              "`SOURCE_SHA`/`FIXTURE_SHA`. They are the behavioural contract for the",
              "`stored_logic` unit: the rewritten logic must reproduce them, and they are",
              "independent of the data-parity recon.", ""]

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
