apiVersion: v1
kind: ConfigMap
metadata:
  name: oncall-datasources
  namespace: monitoring
  labels:
    grafana_datasource: "1"
    app.kubernetes.io/part-of: oncall-storm
data:
  oncall-datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        uid: loki
        access: proxy
        url: http://oncall-loki.monitoring.svc.cluster.local:3100
        editable: false
        jsonData:
          maxLines: 1000
      - name: Tempo
        type: tempo
        uid: tempo
        access: proxy
        url: http://oncall-tempo.monitoring.svc.cluster.local:3200
        editable: false
        jsonData:
          tracesToLogsV2:
            datasourceUid: loki
            tags: [{key: k8s.namespace.name, value: namespace}, {key: service.name, value: app}]
            spanStartTimeShift: -1m
            spanEndTimeShift: 1m
