-- Legal-hold audit trail: every change of DOCARCH.LEGAL_HOLD_FLAG writes a HOLD/RLSE event into
-- FILEAUD from inside the same transaction. Fires only on UPDATE OF LEGAL_HOLD_FLAG, so the bulk
-- seed (INSERT only) never pays for it.
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE SEQUENCE ARCHIVE.SEQ_FILEAUD_TRG START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE TRIGGER ARCHIVE.TRG_DOCARCH_HOLD_AUDIT
AFTER UPDATE OF LEGAL_HOLD_FLAG ON ARCHIVE.DOCARCH
FOR EACH ROW
WHEN (NEW.LEGAL_HOLD_FLAG <> OLD.LEGAL_HOLD_FLAG)
DECLARE
    v_actor  VARCHAR2(12) := SUBSTR(SYS_CONTEXT('USERENV', 'SESSION_USER'), 1, 12);
    v_ip     VARCHAR2(15) := SUBSTR(NVL(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), '0.0.0.0'), 1, 15);
BEGIN
    INSERT INTO ARCHIVE.FILEAUD (
        AUDIT_KEY, ARCH_KEY, EVENT_TYPE, EVENT_TS, ACTOR_ID, RETENTION_CLASS,
        DISPOSITION_CODE, CLIENT_IP, DETAIL_TEXT)
    VALUES (
        'TRG' || LPAD(TO_CHAR(ARCHIVE.SEQ_FILEAUD_TRG.NEXTVAL), 17, '0'),
        :NEW.ARCH_KEY,
        DECODE(:NEW.LEGAL_HOLD_FLAG, 'Y', 'HOLD', 'RLSE'),
        SYSTIMESTAMP,
        v_actor,
        :NEW.RETENTION_CLASS,
        ARCHIVE.RETENTION_PKG.DISPOSITION_CODE(:NEW.RETENTION_CLASS, :NEW.LAST_ACCESS_TS, :NEW.LEGAL_HOLD_FLAG),
        v_ip,
        SUBSTR(DECODE(:NEW.LEGAL_HOLD_FLAG, 'Y', 'HOLD placed', 'HOLD released') || ' v' || :NEW.VERSION_NO, 1, 40));
END;
/

SHOW ERRORS TRIGGER ARCHIVE.TRG_DOCARCH_HOLD_AUDIT

DECLARE
    v_errors PLS_INTEGER;
BEGIN
    SELECT COUNT(*) INTO v_errors
      FROM DBA_ERRORS
     WHERE OWNER = 'ARCHIVE' AND NAME = 'TRG_DOCARCH_HOLD_AUDIT' AND ATTRIBUTE = 'ERROR';
    IF v_errors > 0 THEN
        RAISE_APPLICATION_ERROR(-20000, 'ARCHIVE.TRG_DOCARCH_HOLD_AUDIT has ' || v_errors || ' compilation error(s)');
    END IF;
END;
/
